resources:
  # TODO: replace this with:
  # 1. bosh_cli installed on the Docker image.
  # 2. the bats (acceptance) pulled out to a separate repo.
  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: concourse

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bosh-init-exe
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: {{aws_s3_release_bucket}}
      region_name: {{aws_s3_release_bucket_region}}
      access_key_id: {{aws_s3_release_bucket_access_key}}
      secret_access_key: {{aws_s3_release_bucket_secret_key}}

  - name: bosh-deployments
    type: git
    source:
      uri: git@github.com:cloudfoundry/deployments-bosh.git
      branch: master
      private_key: {{github_private_key}}

  - name: aws-cpi
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release.git
      branch: master

  - name: aws-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

  - name: openstack-cpi
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release.git
      branch: master

jobs:
  - name: bats-aws-cpi
    plan:
      - aggregate:
        - {get: bats, trigger: false}
        - {get: bosh-init, trigger: false, resource: bosh-init-exe}
        - {get: bosh-deployments, trigger: false}
        - {get: bosh-release, trigger: false}
        - {get: cpi-release, resource: aws-cpi}
        - {get: stemcell, trigger: false, resource: aws-stemcell}
      # - task: clean
      - task: build-cpi
        file: bats/ci/tasks/build-cpi.yml
        config:
          params:
            cpi_release_name: bosh-aws-cpi
#      - task: deploy-bosh
#        file: bats/ci/tasks/deploy-bosh.yml
#        config:
#          params:
#            manifest_path: {{aws_bosh_manifest_path}}
      - put: bosh-deployments
        params:
          repository: deploy-bosh/bosh-deployments
          rebase: true
      - task: run-bats
        file: bats/ci/tasks/run-bats.yml
        config:
          params:
            BAT_DEPLOYMENT_SPEC: {{aws_bats_manifest_path}}
            BAT_DIRECTOR: {{aws_bats_director_address}}
            BAT_DNS_HOST: {{aws_bats_dns_host}}
            BAT_STEMCELL: stemcell/stemcell.tgz
            BAT_INFRASTRUCTURE: aws
            BAT_NETWORKING: manual
            BAT_VCAP_PRIVATE_KEY_PATH: {{bats_vcap_private_key_path}}
            BAT_VCAP_PASSWORD: 'c1oudc0w'
  # - name: bats-openstack-cpi
  #   plan:
  #     - aggregate:
  #       - get: bosh
  #       - get: bosh-init
  #       - get: bosh-deployments
  #       - get: cpi-release
  #         resource: openstack-cpi
  #     - task: deploy-microbosh
  #       file: bosh/bat/ci/tasks/deploy-microbosh.yml
  #       config:
  #         params:
  #           manifest_path: bosh-deployments/concourse/bats-pipeline/micro-openstack.yml
  #     - task: run-bats
  #       file: bosh/bat/ci/tasks/run-bats.yml
